### ISSUE TITLE
DefaultBTreeMap?

### ISSUE THREAD

**Issue by Boscop** [JelteF/defaultmap#2]
Are there any plans to add a DefaultBTreeMap too? Would be useful..

**Comment by JelteF** [comment]
I haven't had the need for it yet myself, so I haven't done it yet. A PR
that implements it is definitely appreciated though. Code should be able to
be quite similar to the hashmap based implementation.

**Comment by JelteF** [comment]
Fixed now with the 0.5.0 release.
